# .project metadata for KEDA
# Documentation: https://github.com/cncf/automation/tree/main/utilities/dot-project

schema_version: "1.0.0"
slug: "keda"
name: "KEDA"
description: "KEDA is a Kubernetes-based Event Driven Autoscaling component. It provides event driven scale for any container running in Kubernetes"
type: "project"
project_lead: "zroubalik"
slack_channels:
  - name: "#keda"
    workspace: "kubernetes"
    link: "https://kubernetes.slack.com/archives/CKZJ36A5D"
    primary: true
  - name: "#keda-dev"
    workspace: "kubernetes"
    link: "https://kubernetes.slack.com/archives/C01JGDP8MB8"
  - name: "#keda-docs"
    workspace: "kubernetes"
    link: "https://kubernetes.slack.com/archives/C03M2DKCS3H"

maturity_log:
  - phase: "sandbox"
    date: "2020-03-12T00:00:00Z"
    issue: "https://github.com/cncf/toc/issues/335"
  - phase: "incubating"
    date: "2021-08-18T00:00:00Z"
    issue: "https://github.com/cncf/toc/pull/622"
  - phase: "graduated"
    date: "2023-08-22T00:00:00Z"
    issue: "https://github.com/cncf/toc/pull/925"

repositories:
  - url: "https://github.com/kedacore/keda"
    primary: true
  - url: "https://github.com/kedacore/charts"
    tags: [distribution]
  - url: "https://github.com/kedacore/http-add-on"
    tags: [addon]
  - url: "https://github.com/kedacore/keda-docs"
    tags: [docs]
  - url: "https://github.com/kedacore/keda-olm-operator"
    tags: [distribution]
  - url: "https://github.com/kedacore/governance"
    tags: [governance]
  - url: "https://github.com/kedacore/samples"
    tags: [samples]
  - url: "https://github.com/kedacore/test-tools"
    tags: [tooling]
  - url: "https://github.com/kedacore/testing-infrastructure"
    tags: [infrastructure]

website: "https://keda.sh/"

artwork: "https://raw.githubusercontent.com/cncf/artwork/main/projects/keda/icon/color/keda-icon-color.svg"

adopters:
  path: "https://github.com/kedacore/.project/blob/main/ADOPTERS.md"

package_managers:
  docker:
    - "ghcr.io/kedacore/keda"
    - "ghcr.io/kedacore/keda-metrics-apiserver"
    - "ghcr.io/kedacore/keda-admission-webhooks"
  helm: "kedacore/keda" # Repository: https://kedacore.github.io/charts

social:
  twitter: "https://twitter.com/kedaorg"

security:
  policy:
    path: "https://github.com/kedacore/keda/blob/main/SECURITY.md"
  contact:
    email: "cncf-keda-maintainers@lists.cncf.io"
    advisory_url: "https://github.com/kedacore/keda/security/advisories/new"

governance:
  contributing:
    path: "https://github.com/kedacore/keda/blob/main/CONTRIBUTING.md"
  code_of_conduct:
    path: "https://github.com/kedacore/.github/blob/main/CODE_OF_CONDUCT.md"

legal:
  license:
    path: "https://github.com/kedacore/keda/blob/main/LICENSE"
  identity_type:
    has_dco: true
    has_cla: false
    dco_url:
      path: "https://developercertificate.org/"

documentation:
  readme:
    path: "https://github.com/kedacore/keda/blob/main/README.md"

landscape:
  category: "Orchestration & Management"
  subcategory: "Scheduling & Orchestration"

# CLOMonitor Score: 94/100
# Documentation: 100 | License: 100 | Best Practices: 100 | Security: 68
