name: Update Landscape
on:
  push:
    branches: [main]
    paths:
      - 'project.yaml'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Update Landscape
        uses: cncf/automation/.github/actions/landscape-update@d7d25c42f9247f6e4a0f0a99344432c3bbf3447d
        with:
          project_file: 'project.yaml'
          token: ${{ secrets.LANDSCAPE_REPO_TOKEN }}
